### PR TITLE
Update version string

### PR DESCRIPTION
**Pull request by tekktrik**
Updating the version string to be PEP 440 compliant!

### CODE REVIEW

**Comment by tekktrik** [comment]
This will need a simultaneous update to the libraries for changing their versions, so please **APPROVE BUT DO NOT MERGE**.  Thanks!

**Review by tannewt — CHANGES_REQUESTED** [review]
Please add a second replace call for the old pattern. That way you don't need to do it all at once.

**Comment by tekktrik** [comment]
Could you explain what you mean?  Is a second replace needed?

**Comment by tekktrik** [comment]
If I understand correctly, I think the repos will still need their "default" to be `0.0.0+auto.0` so it should be expecting that.

**Comment by tannewt** [comment]
Instead of deleting `line = line.replace("0.0.0-auto.0", library_version)` just add the new version. That way this tooling will work for repos that have been updated and those that haven't. That way you can merge and release this now instead of needing to wait.

**Comment by tekktrik** [comment]
Are you replace both `0.0.0-auto.0` and `0.0.0+auto.0` to version?  I think I follow now.

**Review by tannewt — APPROVED** [review]
Looks good!

**Pull request merged**
