### PR TITLE
Convert from Travis to Github Actions

### LINKED ISSUE #59: Convert CI for this repo from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by lesamouraipourpre**
Closes #59

This PR changes the workflows to use Github Actions instead of Travis

**BREAKING CHANGES**
* This REQUIRES 'Releases' to generate the artifacts not just 'Tags'. I couldn't figure out how to get Actions to trigger a PyPI push based on just a tag. 
* This DOES NOT generate the data directory containing mpy-cross versions. As far as I can tell the `mpy-cross`s in `data/` are not used by anything. They are also out of date as soon as the next tagged release of circuitpython is pushed. They could easily be added if this assumption is incorrect.

**Admin Todo**
If this PR is accepted an admin will need to add PYPI_USERNAME and PYPI_PASSWORD secrets as per the libraries.

**Testing**
The testing so far was part of PR #72 and used the following adjacent repos. Changes were made where necessary to not use `samourai-build-tools` instead of `circuitpython-build-tools` and to upload to the correct PyPI.
https://github.com/lesamouraipourpre/samourai-build-tools
https://pypi.org/project/samourai-build-tools/
https://github.com/lesamouraipourpre/Samourai_CircuitPython_DPS310/tree/samourai-build-tools-test
https://github.com/lesamouraipourpre/Samourai_CircuitPython_DPS310/releases/tag/0.0.1-beta.3
https://pypi.org/project/samourai-circuitpython-dps310/

This is Draft status because I have a nagging feeling it's not quite right and would like some more experienced input.

### CODE REVIEW

**Comment by tannewt** [comment]
I'm happy to merge this in and test it. @kattni can you please double check the pypi passwords are available?

**Comment by kattni** [comment]
They're available as org-level secrets to all Adafruit org repos.

**Comment by tannewt** [comment]
Sorry we never merged this! Would you mind updating it again?

**Comment by lesamouraipourpre** [comment]
Hopefully this still works, I've not re-tested it.

**Review by tannewt — APPROVED** [review]
Let's try it! Thanks!

**Pull request merged**
