### PR TITLE
Factor out version replacement so its shared between individual

### PR DESCRIPTION
**Pull request by tannewt**
files and files in a package.

This fixes the bytes-like error that happens when trying to build
packages.

### CODE REVIEW

**Comment by tannewt** [comment]
I'm gonna pull this since its broken some builds. Feel free to follow up with feedback and I'll do a subsequent pull request.

**Comment by dhalbert** [comment]
Sorry, I keep getting distracted. I eventually would love to have a general routine I can call when I'm doing module freezing. Or, I will just unpack the library .py .zip file and not use submodules.

**Comment by tannewt** [comment]
Would an additional script in circuitpython-build-tools be enough? Would it
just take a file in and place it in a different directory?

**Comment by dhalbert** [comment]
It doesn't have to be its own script. I was going to write a Python script that imported circuitpython_build_tools/build.py and call its routines. I already copy the appropriate .py files from the submodule into a build directory and then run mpy-cross on them. So I'd update the version string before doing that. But if I unpack your .zip files instead then I don't need to do anything. The disadvantage is that all the frozen modules have to be from the same bundle build.

**Pull request merged**
