### PR TITLE
updated bundle naming to match 3.0.0 final release

### PR DESCRIPTION
**Pull request by kattni**

### CODE REVIEW

**Comment by dhalbert** [comment]
I wonder if we should call them "2.x" and "3.x" so people don't get the idea they have to match. @tannewt what do you think?

**Comment by tannewt** [comment]
Fine with me. Better than being out of date.

**Comment by kattni** [comment]
On it.

**Comment by tannewt** [comment]
don't we still want the full tags?

**Comment by dhalbert** [comment]
Do we get semver errors without the tags? But the tags will be out of date if they say 3.0.0.

**Comment by tannewt** [comment]
Pointing to the branches risks building with unreleased code and makes it unclear what version was used. It doesn't help keep it up to date either because the mpy-cross binaries are built into the pypi package which requires a release to update anyway.

**Comment by dhalbert** [comment]
ok, will fix, I didn't realize the tags were used to fetch the versions to build with.

**Pull request merged**
