### PR TITLE
Add 5.x and remove 2.x and 3.x

### PR DESCRIPTION
**Pull request by tannewt**
The libraries may not support the older versions so remove them.

### CODE REVIEW

**Comment by ladyada** [comment]
can we delete 2.x for sure but not 3.x just yet? we're still shipping hardware with 3.x i think - id have to do a sweep to make sure 3.x is completely moved to 4.x on all the testers!

**Comment by tannewt** [comment]
I'd rather not continue to make 3.x bundles because our libraries don't necessarily support 3.x any more. Ideally, they'd only support the current stable (4.x) and unstable (5.x). For 3.x support folks can download older bundles and libraries or upgrade to 4.x.

**Comment by ladyada** [comment]
okidoke - please make sure the support folks know this is coming

**Comment by tannewt** [comment]
@kattni please approve with a link to the FAQ. Thanks!

**Pull request merged**
